componentScriptContent: 
  - xmlizable: 
    - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      →: |
        /*Begin_c8o_AppImport*/
        /*End_c8o_AppImport*/
        /*Begin_c8o_AppDeclaration*/
        	/*End_c8o_AppDeclaration*/
        /*Begin_c8o_AppConstructor*/
        		/*End_c8o_AppConstructor*/
        /*Begin_c8o_AppInitialization*/
                        /* Uncomment the following lines to enable the i18n feature.
                         * You should add a json per language in the assets/i18n folder. */
                        translate.setDefaultLang('en');
                        translate.use(translate.getBrowserLang());
                        
                        /* Uncomment the following lines to enable the custom status bar color. */
                        // statusBar.overlaysWebView(false);
                        // statusBar.backgroundColorByHexString("#000000");
                        // statusBar.styleBlackOpaque();
        			/*End_c8o_AppInitialization*/
        /*Begin_c8o_AppFunction*/
        	/*End_c8o_AppFunction*/
        
tplProjectName: mobilebuilder_tpl_8_3_0_ngx
↓DisplayGoogleDrivePicker [ngx.components.UIActionStack-1723642068753]: 🗏 mobileSharedActions/DisplayGoogleDrivePicker.yaml
↓Configure [ngx.components.PageComponent-1723642068777]: 🗏 mobilePages/Configure.yaml
↓TestOnly [ngx.components.PageComponent-1724657032162]: 🗏 mobilePages/TestOnly.yaml
↓Style [ngx.components.UIStyle-1723648569770]: 
  comment: You can add some global application styles here
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          'ion-menu ion-content {
            --background: var(--ion-item-background, var(--ion-background-color, #fff));
          }
          
          ion-menu.md ion-content {
            --padding-start: 8px;
            --padding-end: 8px;
            --padding-top: 20px;
            --padding-bottom: 20px;
          }
          
          ion-menu.md ion-list {
            padding: 20px 0;
          }
          
          ion-menu.md ion-note {
            margin-bottom: 30px;
          }
          
          ion-menu.md ion-list-header,
          ion-menu.md ion-note {
            padding-left: 10px;
          }
          
          ion-menu.md ion-list#inbox-list {
            border-bottom: 1px solid var(--ion-color-step-150, #d7d8da);
          }
          
          ion-menu.md ion-list#inbox-list ion-list-header {
            font-size: 22px;
            font-weight: 600;
          
            min-height: 20px;
          }
          
          ion-menu.md ion-list#labels-list ion-list-header {
            font-size: 16px;
          
            margin-bottom: 18px;
          
            color: #757575;
          
            min-height: 26px;
          }
          
          ion-menu.md ion-item {
            --padding-start: 10px;
            --padding-end: 10px;
            border-radius: 4px;
          }
          
          ion-menu.md ion-item.selected {
            --background: rgba(var(--ion-color-primary-rgb), 0.14);
          }
          
          ion-menu.md ion-item.selected ion-icon {
            color: var(--ion-color-primary);
          }
          
          ion-menu.md ion-item ion-icon {
            color: #616e7e;
          }
          
          ion-menu.md ion-item ion-label {
            font-weight: 500;
          }
          
          ion-menu.ios ion-content {
            --padding-bottom: 20px;
          }
          
          ion-menu.ios ion-list {
            padding: 20px 0 0 0;
          }
          
          ion-menu.ios ion-note {
            line-height: 24px;
            margin-bottom: 20px;
          }
          
          ion-menu.ios ion-item {
            --padding-start: 16px;
            --padding-end: 16px;
            --min-height: 50px;
          }
          
          ion-menu.ios ion-item.selected ion-icon {
            color: var(--ion-color-primary);
          }
          
          ion-menu.ios ion-item ion-icon {
            font-size: 24px;
            color: #73849a;
          }
          
          ion-menu.ios ion-list#labels-list ion-list-header {
            margin-bottom: 8px;
          }
          
          ion-menu.ios ion-list-header,
          ion-menu.ios ion-note {
            padding-left: 16px;
            padding-right: 16px;
          }
          
          ion-menu.ios ion-note {
            margin-bottom: 8px;
          }
          
          ion-note {
            display: inline-block;
            font-size: 16px;
          
            color: var(--ion-color-medium-shade);
          }
          
          ion-item.selected {
            --color: var(--ion-color-primary);
          }
          '
↓LightTheme [ngx.components.UIStyle-1723648569773]: 
  comment: This will define the light theme for the application. This will be selected if the device is in light mode.
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          ':root {
            /** primary **/
            --ion-color-primary: #3880ff;
            --ion-color-primary-rgb: 56, 128, 255;
            --ion-color-primary-contrast: #ffffff;
            --ion-color-primary-contrast-rgb: 255, 255, 255;
            --ion-color-primary-shade: #3171e0;
            --ion-color-primary-tint: #4c8dff;
          
            /** secondary **/
            --ion-color-secondary: #3dc2ff;
            --ion-color-secondary-rgb: 61, 194, 255;
            --ion-color-secondary-contrast: #ffffff;
            --ion-color-secondary-contrast-rgb: 255, 255, 255;
            --ion-color-secondary-shade: #36abe0;
            --ion-color-secondary-tint: #50c8ff;
          
            /** tertiary **/
            --ion-color-tertiary: #5260ff;
            --ion-color-tertiary-rgb: 82, 96, 255;
            --ion-color-tertiary-contrast: #ffffff;
            --ion-color-tertiary-contrast-rgb: 255, 255, 255;
            --ion-color-tertiary-shade: #4854e0;
            --ion-color-tertiary-tint: #6370ff;
          
            /** success **/
            --ion-color-success: #2dd36f;
            --ion-color-success-rgb: 45, 211, 111;
            --ion-color-success-contrast: #ffffff;
            --ion-color-success-contrast-rgb: 255, 255, 255;
            --ion-color-success-shade: #28ba62;
            --ion-color-success-tint: #42d77d;
          
            /** warning **/
            --ion-color-warning: #ffc409;
            --ion-color-warning-rgb: 255, 196, 9;
            --ion-color-warning-contrast: #000000;
            --ion-color-warning-contrast-rgb: 0, 0, 0;
            --ion-color-warning-shade: #e0ac08;
            --ion-color-warning-tint: #ffca22;
          
            /** danger **/
            --ion-color-danger: #eb445a;
            --ion-color-danger-rgb: 235, 68, 90;
            --ion-color-danger-contrast: #ffffff;
            --ion-color-danger-contrast-rgb: 255, 255, 255;
            --ion-color-danger-shade: #cf3c4f;
            --ion-color-danger-tint: #ed576b;
          
            /** dark **/
            --ion-color-dark: #222428;
            --ion-color-dark-rgb: 34, 36, 40;
            --ion-color-dark-contrast: #ffffff;
            --ion-color-dark-contrast-rgb: 255, 255, 255;
            --ion-color-dark-shade: #1e2023;
            --ion-color-dark-tint: #383a3e;
          
            /** medium **/
            --ion-color-medium: #92949c;
            --ion-color-medium-rgb: 146, 148, 156;
            --ion-color-medium-contrast: #ffffff;
            --ion-color-medium-contrast-rgb: 255, 255, 255;
            --ion-color-medium-shade: #808289;
            --ion-color-medium-tint: #9d9fa6;
          
            /** light **/
            --ion-color-light: #f4f5f8;
            --ion-color-light-rgb: 244, 245, 248;
            --ion-color-light-contrast: #000000;
            --ion-color-light-contrast-rgb: 0, 0, 0;
            --ion-color-light-shade: #d7d8da;
            --ion-color-light-tint: #f5f6f9;
          }
          '
↓Theme [ngx.components.UITheme-1723648569776]: 
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          // Ionic Variables and Theming. For more info, please see:
          // http://ionicframework.com/docs/theming/
          
          /** Ionic CSS Variables **/
          
          
↓Font [ngx.components.UIFont-1723648569779]: 
  fontSource: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FontSource
      - com.twinsoft.convertigo.beans.common.FontSource: 
        →: '{"fontId":"saira","fontFamily":"Saira","fontWeight":"400","fontStyle":"normal","fontSubset":"latin"}'
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          'font-family: "Saira";
          font-weight: 400;
          font-style: "normal";
          font-variant: "latin";
          '
↓Font1 [ngx.components.UIFont-1723648569782]: 
  fontSource: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FontSource
      - com.twinsoft.convertigo.beans.common.FontSource: 
        →: '{"fontId":"work-sans","fontFamily":"Work Sans","fontWeight":"400","fontStyle":"normal","fontSubset":"latin"}'
  isDefault: true
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          'font-family: "Work Sans";
          font-weight: 400;
          font-style: "normal";
          font-variant: "latin";
          '